### ISSUE TITLE
Error creating export files

### ISSUE THREAD

**Issue by eltron247** [jfriesne/audiomove#2]
Similar to the other issue regarding creating output directories, audiomove errors out immediately upon importing a file.

The file in question is a 38 track .wav file about 4GB in size and resides on the same drive as the destination file. I've verified that permissions are set appropriately. The program actually creates the temp file successfully but then fails. this can be reproduced with any of the 38 track files I've tried either through individual import or through folder import.

I'm happy to provide the offending file/s and/or if there are debug steps I can perform, I'm happy to try those as well.

Build 1.23 on Windows 10 64bit

**Comment by jfriesne** [comment]
@eltron247 .wav files have a maximum file size of 4GB (due to a limitation of their header-structure, which stores internal offsets into the file as 32-bit values), so my first guess is that you are bumping into that limitation.  Can you try changing the "Output Format" to .W64 instead and then doing the same import again, and see if that works better?

**Comment by eltron247** [comment]
I'm actually trying to output as flac but have also tried outputting wav but selecting the "Split Multitrack files" option hoping to get monos. The input file is 3.71GB

**Comment by jfriesne** [comment]
@eltron247 If you can post a link to the file so I can download it, I'll take a look at it.

**Comment by eltron247** [comment]
https://easyupload.io/wll8le

**Comment by jfriesne** [comment]
@eltron247 Converting that file seems to work for me (as long as I set the output settings to ones that the FLAC format actually supports).  Can you send me a screenshot of your AudioMove settings (at the top of the GUI) and also let me know the exact length of the AudioMove.exe you are using (for the record, my AudioMove.exe is 11,791,816 bytes)

**Comment by eltron247** [comment]
[<a href="https://ibb.co/2htfcc2"><img src="https://i.ibb.co/dM2zkk9/Screenshot-2022-06-21-202828.png" alt="Screenshot-2022-06-21-202828" border="0" /></a>](url)

My file size is the same. 11,791,816 bytes  CRC64 is: 0B5A6B47B25DB721


Edited:
<a href="https://ibb.co/Y8vxYf2"><img src="https://i.ibb.co/gwsxHty/Screenshot-2022-06-21-203319.png" alt="Screenshot-2022-06-21-203319" border="0" /></a>

**Comment by jfriesne** [comment]
@eltron247 one thing I just learned (after reproducing the fault and tracing it down through the guts of libsndfile) is that the FLAC audio format doesn't support more than 8 channels per audio file.... which would explain why AudioMove can't create a 38-track FLAC file (although it should work if you check the "Split Multi-Track Files" checkbox, since then there would be 38 mono FLAC files produced instead)

From https://xiph.org/flac/faq.html :
   Q: How many channels does FLAC support?
   A: FLAC supports from 1 to 8 channels per stream
   
 From libsndfile's sf_format_check() function:
 
                 case SF_FORMAT_FLAC :
                               /* FLAC can't do more than 8 channels. */
                                if (info->channels > 8)
                                        return 0 ;

**Comment by eltron247** [comment]
That makes two of us! Thanks for tracking that down so quickly. Any way to both notify of such and offer an output option for channel count? IE Output Channels: 1,2,3,4,5,6,7,8. I fully understand that this is far outside of the scope of this issue and I appreciate the opportunity to learn what the issue was. 

On second thought, and with your permission I'll open a feature request for both that and another thing that would make my world so much easier; output directory same as input without overwrite.

**Comment by jfriesne** [comment]
@eltron247 I think the main problem with making AudioMove "smart" about which features it offers for which format is that AFAIK libsndfile doesn't provide that information in any kind of programmatic fashion; i.e. the only way to find out if libsndfile will open a file with a given combination of settings to call `sf_open()` (or `sf_format_check()`) with those settings and see if it succeeds or not.

Therefore conveying all the various limitations to the user would require manually gathering them from the libsndfile source code and encoding them in some kind of lookup-table, which would be both tedious and difficult to maintain.

It might be possible in some cases for libsndfile to call `sf_format_check()` in advance (e.g. whenever the settings combo boxes change), and let the user know if `sf_format_check()` failed (of course this would only work for explicit settings, since the "Source" options refer to settings that aren't known until the input file is read anyway)
